apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
patchesStrategicMerge:
- adservice-deployment-patch.yaml
- cartservice-deployment-patch.yaml
- frontend-deployment-patch.yaml
- checkoutservice-deployment-patch.yaml
- currencyservice-deployment-patch.yaml
- emailservice-deployment-patch.yaml
- redis-deployment-patch.yaml
- loadgenerator-deployment-patch.yaml  
- productcatalogservice-deployment-patch.yaml 
- shippingservice-deployment-patch.yaml
- paymentservice-deployment-patch.yaml 
- recommendationservice-deployment-patch.yaml 
#- secret_pull_harbor.yaml