apiVersion: apps/v1
kind: Deployment
metadata:
  name: currencyservice
spec:
  replicas: 2 
  template:
    metadata:
      labels:
        app: currencyservice
    spec:
      containers:
      - name: server
        image: vinaydevopslearning/currencyservice:v1
        ports:
        - name: grpc
          containerPort: 7000
        env:
        - name: PORT
          value: "7000"
