apiVersion: apps/v1
kind: Deployment
metadata:
  name: paymentservice
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: paymentservice
    spec:
      containers:
      - name: server
        image: vinaydevopslearning/paymentservice:v1
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"
