apiVersion: apps/v1
kind: Deployment
metadata:
  name: shippingservice
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: shippingservice
    spec:
      containers:
      - name: server
        image: vinaydevopslearning/shippingservice:v1
        ports:
        - containerPort: 50051
        env:
        - name: PORT
          value: "50051"