apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: cartservice
    spec:
      containers:
      - name: server
        image: gkulshre/cartservice:v1
        ports:
        - containerPort: 7070
        env:
        - name: REDIS_ADDR
          value: "redis-cart:6379"