apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: emailservice
    spec:
      containers:
      - name: server
        image: vinaydevopslearning/emailservices:v1
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        # - name: DISABLE_TRACING
        #   value: "1"
        - name: DISABLE_PROFILER
          value: "1"